### PR TITLE
Dictionary case sensitive comparison fix

### LINKED ISSUE #18: Case Sensitive Dictionary Json Settings
I use case insensitive json settings for dictionaries and i set it on my owin startup 
`new KeyValuePairConverter()`

```c#
JsonConvert.DefaultSettings = () => JsonSettings.Tolerant;
```

```c#
public static readonly JsonSerializerSettings Tolerant = new JsonSerializerSettings
        {
            Formatting = Formatting.Indented,
            NullValueHandling = NullValueHandling.Ignore,
            MissingMemberHandling = MissingMemberHandling.Ignore,
            TypeNameHandling = TypeNameHandling.None,
            ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
            PreserveReferencesHandling = PreserveReferencesHandling.None,
            ContractResolver = new CamelCasePropertyNamesContractResolver(),
            Converters = new List<JsonConverter>{
                    new IsoDateTimeConverter(),
                    new KeyValuePairConverter()
                }
        };
```
And i have exception when click the details on dashboard. When dictionary deserialized, its contains lowercase keys and throw key not found exception.

```c#
        public JobDetailsDto JobDetails(string jobId)
        {
            return UseConnection(redis =>
            {
                var job = redis.HashGetAll(String.Format(RedisStorage.Prefix + "job:{0}", jobId)).ToStringDictionary();
                if (job.Count == 0) return null;

                var hiddenProperties = new[] { "Type", "Method", "ParameterTypes", "Arguments", "State", "CreatedAt" };

                var historyList = redis.ListRange(String.Format(RedisStorage.Prefix + "job:{0}:history", jobId))
					.Select(x=> (string)x).ToList();

                var history = historyList
                    .Select(JobHelper.FromJson<Dictionary<string, string>>)
                    .ToList();

                var stateHistory = new List<StateHistoryDto>(history.Count);
                foreach (var entry in history)
                {

                   // Dictionary give key not found also its contain lowercase keys
                    var dto = new StateHistoryDto
                    {
                        StateName = entry["State"],
                        Reason = entry.ContainsKey("Reason") ? entry["Reason"] : null,
                        CreatedAt = JobHelper.DeserializeDateTime(entry["CreatedAt"]),
                    };
....
```
I will think tommorrow someting. Good night.

### PR DESCRIPTION
**Pull request by VictorTomaili**
There is solution for my issue. Fixed #18

### CODE REVIEW

**Comment by VictorTomaili** [comment]
Ohh, thats not my fault :smile:

**Comment by marcoCasamento** [comment]
I Know, sorry for that! I'll try to fix it tomorrow and review your PR too, thanks!! good night

**Comment by marcoCasamento** [comment]
It now builds on windows, see (https://ci.appveyor.com/project/marcoCasamento/hangfire-redis-stackexchange/build/1.0.95)  but your PR seems to fail on some tests, due to type loading errors.
Nuget dependency update needs a bit more work than simply changing packages.config, but it's already done on dev branch (I plan to merge it this weekend), could you remove the packages config and try again ? (or, if you need the packages update right now, make the PR toward dev branch)

**Comment by VictorTomaili** [comment]
i revert nuget update temporary.

**Comment by marcoCasamento** [comment]
Ok great, I've tried locally and it works.PR just merged and nuget package published. Thanks

**Pull request merged**
