### PR TITLE
Compatibility to NetStandard1_6/DotNetCore

### PR DESCRIPTION
**Pull request by Poly3k**
We have a new application which builds upon the new .Net standard framework. Hangfire and Redis are already compatible with that, this adapter is not. With a few changes i made it compatible. Also, the project structure is now ported to the much cleaner xproj version.

### CODE REVIEW

**Comment by marcoCasamento** [comment]
Hi Poly3k thanks for your PR, really valuable.
Travis build is not properly configured (shame on me) but appveyor should build. It complains about xunit, do you have any insight ?

**Comment by Poly3k** [comment]
Hi marcoCasamento,
No problem. There is still some room for improvement, i think i will add some commits later this week. (There are two warnings i could get rid off, but it's nothing that breaks the code). I am sadly not experienced with appveyor, but I maybe found some fixes for the tests. FYI: The tests run fine locally

**Comment by marcoCasamento** [comment]
Great, merging.

**Comment by marcoCasamento** [comment]
I believe we should pump the version and align to that of hangfire.core

**Comment by Poly3k** [comment]
I would agree with that. It will help people. But you are the master, it's your call.
Just to be sure (it's my first pull request i made so far). You closed the request but did not merge the branch, is that correct?

**Comment by marcoCasamento** [comment]
not at all!I didn't want to close it, sorry! Just merged NOW.

About the version, I'll run the code locally in the next few hours, then bump the version and align the nuget package

**Comment by Poly3k** [comment]
Great! Thanks for your support on this one, I hope it'll help the users!

**Pull request merged**
